# Generated by Django 3.2.16 on 2023-11-14 07:28

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_follow_user==following'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user==following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following')), _negated=True), name='user!=following'),
        ),
    ]
